
package co.edu.javeriana.Cliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomerService", targetNamespace = "http://www.ABC.com/CustomerService/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CustomerService {


    /**
     * 
     * @param headerReq
     * @param headerRes
     * @param consulta
     * @return
     *     returns co.edu.javeriana.Cliente.ConsultarClienteRes
     */
    @WebMethod(operationName = "Consultar")
    @WebResult(name = "consultarClienteRes", targetNamespace = "http://www.ABC.com/schemaCustomer", partName = "consultaRes")
    public ConsultarClienteRes consultar(
        @WebParam(name = "consultarClienteReq", targetNamespace = "http://www.ABC.com/schemaCustomer", partName = "consulta")
        ConsultarClienteReq consulta,
        @WebParam(name = "headerReq", targetNamespace = "http://www.ABC.com/schemaHeader", header = true, partName = "headerReq")
        HeaderReq headerReq,
        @WebParam(name = "headerRes", targetNamespace = "http://www.ABC.com/schemaHeader", header = true, mode = WebParam.Mode.OUT, partName = "headerRes")
        Holder<HeaderRes> headerRes);

    /**
     * 
     * @param headerReq
     * @param headerRes
     * @param consultaProd
     * @return
     *     returns co.edu.javeriana.Cliente.ConsultarProdClienteRes
     */
    @WebMethod(operationName = "ConsultarProd")
    @WebResult(name = "consultarProdClienteRes", targetNamespace = "http://www.ABC.com/schemaCustomer", partName = "consultaProdRes")
    public ConsultarProdClienteRes consultarProd(
        @WebParam(name = "consultarProdClienteReq", targetNamespace = "http://www.ABC.com/schemaCustomer", partName = "consultaProd")
        ConsultarProdClienteReq consultaProd,
        @WebParam(name = "headerReq", targetNamespace = "http://www.ABC.com/schemaHeader", header = true, partName = "headerReq")
        HeaderReq headerReq,
        @WebParam(name = "headerRes", targetNamespace = "http://www.ABC.com/schemaHeader", header = true, mode = WebParam.Mode.OUT, partName = "headerRes")
        Holder<HeaderRes> headerRes);

}
