
package co.edu.javeriana.Factura;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BillService", targetNamespace = "http://www.ABC.com/BillService/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BillService {


    /**
     * 
     * @param headerReq
     * @param headerRes
     * @param consulta
     * @return
     *     returns co.edu.javeriana.Factura.ConsultarFacturaRes
     */
    @WebMethod(operationName = "Consultar")
    @WebResult(name = "consultarFacturaRes", targetNamespace = "http://www.ABC.com/schemaBill", partName = "consultaRes")
    public ConsultarFacturaRes consultar(
        @WebParam(name = "consultarFacturaReq", targetNamespace = "http://www.ABC.com/schemaBill", partName = "consulta")
        ConsultarFacturaReq consulta,
        @WebParam(name = "headerReq", targetNamespace = "http://www.ABC.com/schemaHeader", header = true, partName = "headerReq")
        HeaderReq headerReq,
        @WebParam(name = "headerRes", targetNamespace = "http://www.ABC.com/schemaHeader", header = true, mode = WebParam.Mode.OUT, partName = "headerRes")
        Holder<HeaderRes> headerRes);

    /**
     * 
     * @param pagar
     * @param headerReq
     * @param headerRes
     * @return
     *     returns co.edu.javeriana.Factura.PagarFacturaRes
     */
    @WebMethod(operationName = "Pagar")
    @WebResult(name = "pagarFacturaRes", targetNamespace = "http://www.ABC.com/schemaBill", partName = "pagarRes")
    public PagarFacturaRes pagar(
        @WebParam(name = "pagarFacturaReq", targetNamespace = "http://www.ABC.com/schemaBill", partName = "pagar")
        PagarFacturaReq pagar,
        @WebParam(name = "headerReq", targetNamespace = "http://www.ABC.com/schemaHeader", header = true, partName = "headerReq")
        HeaderReq headerReq,
        @WebParam(name = "headerRes", targetNamespace = "http://www.ABC.com/schemaHeader", header = true, mode = WebParam.Mode.OUT, partName = "headerRes")
        Holder<HeaderRes> headerRes);

    /**
     * 
     * @param headerReq
     * @param headerRes
     * @param compensar
     * @return
     *     returns co.edu.javeriana.Factura.CompensarFacturaRes
     */
    @WebMethod(operationName = "Compensar")
    @WebResult(name = "compensarFacturaRes", targetNamespace = "http://www.ABC.com/schemaBill", partName = "compensarRes")
    public CompensarFacturaRes compensar(
        @WebParam(name = "compensarFacturaReq", targetNamespace = "http://www.ABC.com/schemaBill", partName = "compensar")
        CompensarFacturaReq compensar,
        @WebParam(name = "headerReq", targetNamespace = "http://www.ABC.com/schemaHeader", header = true, partName = "headerReq")
        HeaderReq headerReq,
        @WebParam(name = "headerRes", targetNamespace = "http://www.ABC.com/schemaHeader", header = true, mode = WebParam.Mode.OUT, partName = "headerRes")
        Holder<HeaderRes> headerRes);

}
