
package co.edu.javeriana.Producto;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductService", targetNamespace = "http://www.ABC.com/ProductService/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductService {


    /**
     * 
     * @param headerReq
     * @param headerRes
     * @param consulta
     * @return
     *     returns co.edu.javeriana.Producto.ConsultarProductoRes
     */
    @WebMethod(operationName = "Consultar")
    @WebResult(name = "consultarProductoRes", targetNamespace = "http://www.ABC.com/schemaProduct", partName = "consultaRes")
    public ConsultarProductoRes consultar(
        @WebParam(name = "consultarProductoReq", targetNamespace = "http://www.ABC.com/schemaProduct", partName = "consulta")
        ConsultarProductoReq consulta,
        @WebParam(name = "headerReq", targetNamespace = "http://www.ABC.com/schemaHeader", header = true, partName = "headerReq")
        HeaderReq headerReq,
        @WebParam(name = "headerRes", targetNamespace = "http://www.ABC.com/schemaHeader", header = true, mode = WebParam.Mode.OUT, partName = "headerRes")
        Holder<HeaderRes> headerRes);

    /**
     * 
     * @param actualiza
     * @param headerReq
     * @param headerRes
     * @return
     *     returns co.edu.javeriana.Producto.ActualizarProductoRes
     */
    @WebMethod(operationName = "Actualizar")
    @WebResult(name = "actualizarProductoRes", targetNamespace = "http://www.ABC.com/schemaProduct", partName = "actualizaRes")
    public ActualizarProductoRes actualizar(
        @WebParam(name = "actualizarProductoReq", targetNamespace = "http://www.ABC.com/schemaProduct", partName = "actualiza")
        ActualizarProductoReq actualiza,
        @WebParam(name = "headerReq", targetNamespace = "http://www.ABC.com/schemaHeader", header = true, partName = "headerReq")
        HeaderReq headerReq,
        @WebParam(name = "headerRes", targetNamespace = "http://www.ABC.com/schemaHeader", header = true, mode = WebParam.Mode.OUT, partName = "headerRes")
        Holder<HeaderRes> headerRes);

}
