
package co.edu.javeriana.Login;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LoginService", targetNamespace = "http://www.ABC.com/LoginService/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LoginService {


    /**
     * 
     * @param autenticarReq
     * @param headerReq
     * @param headerRes
     * @return
     *     returns co.edu.javeriana.Login.LoginRes
     */
    @WebMethod(operationName = "Autenticar")
    @WebResult(name = "LoginRes", targetNamespace = "http://www.ABC.com/schemaLogin", partName = "autenticarRes")
    public LoginRes autenticar(
        @WebParam(name = "LoginReq", targetNamespace = "http://www.ABC.com/schemaLogin", partName = "autenticarReq")
        LoginReq autenticarReq,
        @WebParam(name = "headerReq", targetNamespace = "http://www.ABC.com/schemaHeader", header = true, partName = "headerReq")
        HeaderReq headerReq,
        @WebParam(name = "headerRes", targetNamespace = "http://www.ABC.com/schemaHeader", header = true, mode = WebParam.Mode.OUT, partName = "headerRes")
        Holder<HeaderRes> headerRes);

}
