
package co.edu.javeriana.Log;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LogService", targetNamespace = "http://www.ABC.com/LogService/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LogService {


    /**
     * 
     * @param headerReq
     * @param grabar
     */
    @WebMethod(operationName = "Grabar")
    @Oneway
    public void grabar(
        @WebParam(name = "logReq", targetNamespace = "http://www.ABC.com/schemaLog", partName = "grabar")
        LogReq grabar,
        @WebParam(name = "headerReq", targetNamespace = "http://www.ABC.com/schemaHeader", header = true, partName = "headerReq")
        HeaderReq headerReq);

}
