
package co.edu.javeriana.Notificacion;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NotificationService", targetNamespace = "http://www.ABC.com/NotificationService/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NotificationService {


    /**
     * 
     * @param notificacionReq
     * @param headerReq
     */
    @WebMethod(operationName = "Notificar")
    @Oneway
    public void notificar(
        @WebParam(name = "notificacionReq", targetNamespace = "http://www.ABC.com/schemaNotification", partName = "notificacionReq")
        NotificacionReq notificacionReq,
        @WebParam(name = "headerReq", targetNamespace = "http://www.ABC.com/schemaHeader", header = true, partName = "headerReq")
        HeaderReq headerReq);

}
